### PR TITLE
Fixes from openSUSE

### PR DESCRIPTION
**Pull request by posophe**

### CODE REVIEW

**Comment by leggewie** [comment]
@posophe Thank you very much for pushing your patches upstream.  Much appreciated.  I will mostly defer to @tzhuan to evaluate the patches.  I believe I will have to NAK 9d17405, though at least for the part changing the /Hotkeys/FrontEnd/Trigger  I have made a comment to above commit since I believe Shift+Space is used for a half-width space in Japanese.

**Comment by posophe** [comment]
Maybe you're right :). The only thing i'm sure with is it's the default configuration on Fedora and OpenSUSE

**Comment by leggewie** [comment]
Are you the maintainer of those packages or just a friendly user pushing some downstream patches for inclusion?

**Comment by posophe** [comment]
The second. I'm updating scim and scim-tables in openSUSE

**Comment by leggewie** [comment]
@tzhuan Debian uses a more sophisticated configuration (differentiating between the different languages).  And indeed, Shift+Space is not used to trigger in Japanese.  We should probably include those patches upstream for the benefit of everyone.

**Comment by posophe** [comment]
Would be a good thing :)

**Comment by tzhuan** [comment]
It is fine for the first patch (no-setpwent one). However, I am not so sure for the second one. While I am a Chinese user, I can confirm that Shift+Space is the default short-key to switch full-width/half-width mode in both Windows and Mac OS X. Setting it to other function globally might break the user experience for Chinese users from Windows/OS X. I am considering to provide different default configuration for different languages. Could you please split the patches into two pull-request so that I can merge the no-setpwent one first? Thanks.

**Comment by leggewie** [comment]
It was easy enough to push 697d8c8 so I went ahead and did it.  I dropped the unrelated part of changing triggers in 9d17405 and then pushed that as well.  Changes to the Trigger and possibly making that language-dependent need to be done in another commit.  Thank you for your contributions.

**Comment by tzhuan** [comment]
Thanks!

**Pull request closed without merging**
