### PR TITLE
WIP: Qt5 Input Method Plugin.

### PR DESCRIPTION
**Pull request by heroxbd**
I have adopted SCIM Qt4 code to Qt5.  It compiles well, and can be loaded by Qt5 application.  But SCIM cannot be activated. @tzhuan Would you please have a look?

Thanks!
Benda

### CODE REVIEW

**Comment by heroxbd** [comment]
@marguerite, would you please help review the code with your expertise on scim-bridge? Thank you very much!

**Comment by tzhuan** [comment]
Thank you very much for the porting. While I know nothing about Qt I'll try my best to read the codes.

**Comment by heroxbd** [comment]
> Thank you very much for the porting. While I know nothing about Qt I'll try my best to read the codes.

No worries, my change does not have any real content.  At present its just letting it compile against Qt5 libraries.  In the mean time, I am trying to understand the reason why SCIM is not activated in the Qt5 programs.

The applications I am using to test are QTerm and juffed.

**Comment by heroxbd** [comment]
> I have adopted SCIM Qt4 code to Qt5. It compiles well, and can be loaded by Qt5 application. But SCIM cannot be activated. @tzhuan Would you please have a look?

I was not correct.  Further tests show that the Qt5 port is at least not worse than the Qt4 counterpart.  I re-added the Ctrl-Space as the activation hotkey and SCIM can input Chinese to Qt5 applications.

Tested with `QTerm`.  

`juffed` cannot accept input methods not only SCIM, there seems to be some bug in `scintilla`. But that's not our business.

**Comment by tzhuan** [comment]
Thank you!

**Pull request merged**
